from django.db import models

# Create your models here.
class user(models.Model):
    objects = models.Manager()
    userID = models.CharField(primary_key=True,max_length=12)
    userPWD = models.CharField(max_length=18)
    status = models.CharField(max_length=10)
class department(models.Model):
    objects = models.Manager()
    aca_id = models.CharField(primary_key=True,max_length=20)
    aca_name = models.CharField(max_length=50)
class major(models.Model):
    objects = models.Manager()
    acamaj_id =models.CharField(primary_key=True,max_length=30)
    aca_id = models.ForeignKey(department,on_delete=models.CASCADE)
    maj_id = models.CharField(max_length=10)
    maj_name = models.CharField(max_length=50)
    maj_location = models.CharField(max_length=100,blank=True,null=True)
class student(models.Model):
    objects = models.Manager()
    gender = (( "男",'male'),( "女",'female'),)
    std_id = models.CharField(primary_key=True,max_length=20)
    std_name = models.CharField(max_length=50)
    std_sex = models.CharField(max_length=10, choices=gender,blank=True,null=True)
    std_age = models.DateField(blank=True,null=True)
    std_date = models.DateField()
    aca_id = models.ForeignKey(department,on_delete=models.CASCADE,max_length=20)
    maj_id = models.CharField(max_length=10)
    std_grade = models.IntegerField(blank=True,null=True)
    std_class = models.IntegerField(blank=True,null=True)
    std_IDcard = models.CharField(max_length=20)
class teacher(models.Model):
    objects = models.Manager()
    gender = (( "男",'male'),("女",'female'),)
    tea_id = models.CharField(primary_key=True,max_length=20)
    tea_name = models.CharField(max_length=50)
    tea_sex = models.CharField(max_length=10, choices=gender,null=True)
    tea_age = models.DateField(blank=True,null=True)
    tea_title = models.CharField(blank=True,null=True,max_length=20)
    aca_id = models.ForeignKey(department,on_delete=models.CASCADE)
class course(models.Model):
    objects = models.Manager()
    cou_id = models.CharField(primary_key=True,max_length=20)
    cou_name = models.CharField(max_length=50)
    cou_credit = models.IntegerField()
    cou_fid = models.CharField(blank=True,null=True,max_length=20)
class setupcourse(models.Model):
    objects = models.Manager()
    coubeg_id = models.CharField(max_length=30,primary_key=True)
    cou_id = models.ForeignKey(course,on_delete=models.CASCADE,max_length=20)
    beg_id = models.IntegerField()
    beg_term = models.IntegerField(blank=True,null=True)
    tea_id = models.ForeignKey(teacher,on_delete=models.CASCADE)
class selectcourse(models.Model):
    objects = models.Manager()
    cbs_id = models.CharField(primary_key=True,max_length=60)
    cou_id = models.ForeignKey(course,on_delete=models.CASCADE,max_length=20)
    beg_id = models.IntegerField()
    std_id = models.ForeignKey(student,on_delete=models.CASCADE,max_length=20)
    cou_score = models.IntegerField(blank=True,null=True)
class rap(models.Model):
    objects = models.Manager()
    gender = (("奖项",'reward'),("惩罚",'punishment'))
    rap_id = models.IntegerField(primary_key=True)
    std_id = models.ForeignKey(student,on_delete=models.CASCADE)
    rap_rop = models.CharField(max_length=10,choices=gender)
    rap_name = models.CharField(max_length=50)
    rap_level = models.CharField(blank=True,null=True,max_length=10)
    rap_year = models.IntegerField(blank=True,null=True)
    rap_else = models.CharField(max_length=100,blank=True,null=True)