# Generated by Django 3.0 on 2019-12-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cou_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cou_name', models.CharField(max_length=50)),
                ('cou_credit', models.IntegerField()),
                ('cou_fid', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('aca_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('aca_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('acamaj_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('aca_id', models.CharField(max_length=20)),
                ('maj_id', models.CharField(max_length=10)),
                ('maj_name', models.CharField(max_length=50)),
                ('maj_location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='selectcourse',
            fields=[
                ('cbs_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('cou_id', models.CharField(max_length=20)),
                ('beg_id', models.CharField(max_length=20)),
                ('std_id', models.CharField(max_length=20)),
                ('cou_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('std_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=50)),
                ('std_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, null=True)),
                ('std_age', models.DateField(null=True)),
                ('std_date', models.DateField()),
                ('aca_id', models.CharField(max_length=20)),
                ('maj_id', models.CharField(max_length=10)),
                ('std_grade', models.IntegerField(null=True)),
                ('std_class', models.IntegerField(null=True)),
                ('std_IDcard', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('tea_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tea_name', models.CharField(max_length=50)),
                ('tea_sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, null=True)),
                ('tea_age', models.DateField(null=True)),
                ('tea_title', models.CharField(max_length=20, null=True)),
                ('aca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.department')),
            ],
        ),
        migrations.CreateModel(
            name='setupcourse',
            fields=[
                ('coubeg_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cou_id', models.CharField(max_length=20)),
                ('beg_id', models.CharField(max_length=10)),
                ('beg_term', models.IntegerField(null=True)),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='rap',
            fields=[
                ('rap_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rap_rop', models.CharField(choices=[('rewards', '奖项'), ('punishment', '惩罚')], max_length=10)),
                ('rap_name', models.CharField(max_length=50)),
                ('rap_level', models.CharField(max_length=10, null=True)),
                ('rap_year', models.IntegerField(null=True)),
                ('rap_else', models.CharField(max_length=100, null=True)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.student')),
            ],
        ),
    ]
