# Generated by Django 3.0 on 2019-12-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20191219_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_sex',
            field=models.CharField(blank=True, choices=[('男', 'male'), ('女', 'female')], max_length=10, null=True),
        ),
    ]
