# Generated by Django 3.0 on 2019-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_auto_20191219_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rap',
            name='rap_rop',
            field=models.CharField(choices=[('奖项', 'rewards'), ('惩罚', 'punishment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tea_sex',
            field=models.CharField(choices=[('男', 'male'), ('女', 'female')], max_length=10, null=True),
        ),
    ]
