# Generated by Django 3.0 on 2019-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20191221_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectcourse',
            name='beg_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setupcourse',
            name='beg_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='setupcourse',
            name='coubeg_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
